services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        WWWUSER: wwwuser
        WWWGROUP: www-data
        WWWUID: ${UID}
        WWWGID: ${GID}
    container_name: web
    volumes:
      - .:/var/www:cached
    expose:
      - 9000
    working_dir: /var/www

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 
    #--loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

volumes:
  pgdata:
  cache: